
// Generated by Cadence Genus(TM) Synthesis Solution 22.14-s059_1
// Generated on: Jan 15 2025 14:57:58 -03 (Jan 15 2025 17:57:58 UTC)

// Verification Directory fv/decodificador_pt2272 

module decodificador_pt2272(clk, reset, A, cod_i, D, dv);
  input clk, reset, cod_i;
  input [7:0] A;
  output [3:0] D;
  output dv;
  wire clk, reset, cod_i;
  wire [7:0] A;
  wire [3:0] D;
  wire dv;
  wire [7:0] A_01;
  wire [7:0] A_F;
  wire [31:0] regSign;
  wire [7:0] A_F_ff;
  wire [7:0] A_01_ff;
  wire [2:0] counterSync_ff;
  wire [4:0] regSignCount_ff;
  wire [3:0] current_state;
  wire [3:0] registerD_ff;
  wire [2:0] counterD_ff;
  wire [6:0] inst_freq_div_counter;
  wire [3:0] counterA_ff;
  wire dv_s, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_129, n_130, n_131, n_132, n_133, n_134;
  wire n_135, n_136, n_137, n_138, n_139, n_140, n_141, n_142;
  wire n_143, n_144, n_145, n_146, n_147, n_148, n_149, n_150;
  wire n_151, n_152, n_153, n_154, n_155, n_156, n_157, n_158;
  wire n_159, n_160, n_161, n_162, n_163, n_164, n_165, n_166;
  wire n_167, n_168, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, osc_12;
  comp_endereco inst_comp_endereco(.A (A), .A_01 (A_01), .A_F (A_F));
  DFFRHQX1 \regSign_reg[31] (.RN (n_8), .CK (osc_12), .D (regSign[30]),
       .Q (regSign[31]));
  DFFRHQX1 \regSign_reg[30] (.RN (n_8), .CK (osc_12), .D (regSign[29]),
       .Q (regSign[30]));
  DFFRHQX1 \regSign_reg[29] (.RN (n_8), .CK (osc_12), .D (regSign[28]),
       .Q (regSign[29]));
  DFFRHQX1 \regSign_reg[28] (.RN (n_8), .CK (osc_12), .D (regSign[27]),
       .Q (regSign[28]));
  DFFRHQX1 \regSign_reg[27] (.RN (n_8), .CK (osc_12), .D (regSign[26]),
       .Q (regSign[27]));
  DFFRHQX1 \regSign_reg[26] (.RN (n_8), .CK (osc_12), .D (regSign[25]),
       .Q (regSign[26]));
  DFFRHQX1 \regSign_reg[25] (.RN (n_8), .CK (osc_12), .D (regSign[24]),
       .Q (regSign[25]));
  DFFRHQX1 \regSign_reg[24] (.RN (n_8), .CK (osc_12), .D (regSign[23]),
       .Q (regSign[24]));
  DFFRHQX1 \regSign_reg[23] (.RN (n_8), .CK (osc_12), .D (regSign[22]),
       .Q (regSign[23]));
  DFFRHQX1 \regSign_reg[22] (.RN (n_8), .CK (osc_12), .D (regSign[21]),
       .Q (regSign[22]));
  DFFRHQX1 \regSign_reg[21] (.RN (n_8), .CK (osc_12), .D (regSign[20]),
       .Q (regSign[21]));
  DFFRHQX1 \regSign_reg[20] (.RN (n_8), .CK (osc_12), .D (regSign[19]),
       .Q (regSign[20]));
  DFFRHQX1 \regSign_reg[19] (.RN (n_8), .CK (osc_12), .D (regSign[18]),
       .Q (regSign[19]));
  DFFRHQX1 \regSign_reg[18] (.RN (n_8), .CK (osc_12), .D (regSign[17]),
       .Q (regSign[18]));
  DFFRHQX1 \regSign_reg[17] (.RN (n_8), .CK (osc_12), .D (regSign[16]),
       .Q (regSign[17]));
  DFFRHQX1 \regSign_reg[16] (.RN (n_8), .CK (osc_12), .D (regSign[15]),
       .Q (regSign[16]));
  DFFRHQX1 \regSign_reg[15] (.RN (n_8), .CK (osc_12), .D (regSign[14]),
       .Q (regSign[15]));
  DFFRHQX1 dv_reg(.RN (n_8), .CK (osc_12), .D (n_205), .Q (dv));
  DFFRHQX1 \regSign_reg[14] (.RN (n_8), .CK (osc_12), .D (regSign[13]),
       .Q (regSign[14]));
  DFFRHQX1 \regSign_reg[13] (.RN (n_8), .CK (osc_12), .D (regSign[12]),
       .Q (regSign[13]));
  INVXL g6622(.A (dv_s), .Y (n_205));
  OR4X1 g6623__2398(.A (n_171), .B (n_207), .C (n_206), .D (n_204), .Y
       (dv_s));
  DFFRHQX1 \regSign_reg[12] (.RN (n_8), .CK (osc_12), .D (regSign[11]),
       .Q (regSign[12]));
  DFFRHQX1 \regSign_reg[11] (.RN (n_8), .CK (osc_12), .D (regSign[10]),
       .Q (regSign[11]));
  DFFRHQX1 \regSign_reg[10] (.RN (n_8), .CK (osc_12), .D (regSign[9]),
       .Q (regSign[10]));
  OAI211X1 g6627__5107(.A0 (n_168), .A1 (A_F_ff[3]), .B0 (n_182), .C0
       (n_203), .Y (n_204));
  DFFRHQX1 \regSign_reg[9] (.RN (n_8), .CK (osc_12), .D (regSign[8]),
       .Q (regSign[9]));
  DFFRHQX1 \regSign_reg[8] (.RN (n_8), .CK (osc_12), .D (regSign[7]),
       .Q (regSign[8]));
  NOR4X1 g6630__6260(.A (n_195), .B (n_196), .C (n_201), .D (n_202), .Y
       (n_203));
  DFFRHQX1 \regSign_reg[7] (.RN (n_8), .CK (osc_12), .D (regSign[6]),
       .Q (regSign[7]));
  DFFRHQX1 \regSign_reg[6] (.RN (n_8), .CK (osc_12), .D (regSign[5]),
       .Q (regSign[6]));
  DFFRHQX1 \regSign_reg[5] (.RN (n_8), .CK (osc_12), .D (regSign[4]),
       .Q (regSign[5]));
  OAI211X1 g6634__4319(.A0 (n_174), .A1 (A_01_ff[2]), .B0 (n_190), .C0
       (n_200), .Y (n_202));
  OAI211X1 g6635__8428(.A0 (n_179), .A1 (A_01_ff[7]), .B0 (n_192), .C0
       (n_199), .Y (n_201));
  DFFRHQX1 \regSign_reg[4] (.RN (n_8), .CK (osc_12), .D (regSign[3]),
       .Q (regSign[4]));
  AOI211XL g6637__5526(.A0 (n_175), .A1 (A_01_ff[0]), .B0 (n_189), .C0
       (n_198), .Y (n_200));
  AOI211XL g6638__6783(.A0 (n_173), .A1 (A_01_ff[5]), .B0 (n_188), .C0
       (n_197), .Y (n_199));
  DFFRHQX1 \regSign_reg[3] (.RN (n_8), .CK (osc_12), .D (regSign[2]),
       .Q (regSign[3]));
  NAND3BXL g6640__3680(.AN (n_208), .B (counterSync_ff[1]), .C
       (counterSync_ff[0]), .Y (n_206));
  OAI211X1 g6641__1617(.A0 (n_178), .A1 (A_01_ff[3]), .B0 (n_191), .C0
       (n_194), .Y (n_198));
  OAI211X1 g6642__2802(.A0 (n_172), .A1 (A_01_ff[4]), .B0 (n_187), .C0
       (n_193), .Y (n_197));
  NAND4XL g6643__1705(.A (n_185), .B (n_181), .C (n_186), .D (n_180),
       .Y (n_196));
  NAND2XL g6644__5122(.A (n_184), .B (n_183), .Y (n_195));
  DFFRHQX1 \regSign_reg[2] (.RN (n_8), .CK (osc_12), .D (regSign[1]),
       .Q (regSign[2]));
  XNOR2X1 g6646__8246(.A (n_170), .B (A_01_ff[1]), .Y (n_194));
  XNOR2X1 g6647__7098(.A (n_176), .B (A_01_ff[6]), .Y (n_193));
  NAND4XL g6648__6131(.A (regSignCount_ff[2]), .B (regSignCount_ff[0]),
       .C (regSignCount_ff[3]), .D (n_177), .Y (n_208));
  NAND2XL g6649__1881(.A (n_179), .B (A_01_ff[7]), .Y (n_192));
  NAND2XL g6650__5115(.A (n_178), .B (A_01_ff[3]), .Y (n_191));
  NAND2XL g6651__7482(.A (n_174), .B (A_01_ff[2]), .Y (n_190));
  NOR2XL g6652__4733(.A (n_175), .B (A_01_ff[0]), .Y (n_189));
  NOR2XL g6653__6161(.A (n_173), .B (A_01_ff[5]), .Y (n_188));
  NAND2XL g6654__9315(.A (n_172), .B (A_01_ff[4]), .Y (n_187));
  DFFRHQX1 \regSign_reg[1] (.RN (n_8), .CK (osc_12), .D (regSign[0]),
       .Q (regSign[1]));
  XNOR2X1 g6656__9945(.A (A_F[7]), .B (A_F_ff[7]), .Y (n_186));
  XNOR2X1 g6657__2883(.A (A_F[6]), .B (A_F_ff[6]), .Y (n_185));
  XNOR2X1 g6658__2346(.A (A_F[0]), .B (A_F_ff[0]), .Y (n_184));
  XNOR2X1 g6659__1666(.A (A_F[2]), .B (A_F_ff[2]), .Y (n_183));
  XNOR2X1 g6660__7410(.A (A_F[1]), .B (A_F_ff[1]), .Y (n_182));
  XNOR2X1 g6661__6417(.A (A_F[4]), .B (A_F_ff[4]), .Y (n_181));
  XNOR2X1 g6662__5477(.A (A_F[5]), .B (A_F_ff[5]), .Y (n_180));
  AND2X1 g6663__2398(.A (regSignCount_ff[4]), .B (regSignCount_ff[1]),
       .Y (n_177));
  NAND2BXL g6664__5107(.AN (A_F[7]), .B (A_01[7]), .Y (n_179));
  NAND2XL g6665__6260(.A (A_01[3]), .B (n_168), .Y (n_178));
  DFFRHQX1 \regSign_reg[0] (.RN (n_8), .CK (osc_12), .D (cod_i), .Q
       (regSign[0]));
  NOR2BX1 g6667__4319(.AN (A_01[6]), .B (A_F[6]), .Y (n_176));
  NAND2BXL g6668__8428(.AN (current_state[0]), .B (current_state[1]),
       .Y (n_207));
  AND2X1 g6669__5526(.A (A_F_ff[3]), .B (n_168), .Y (n_171));
  NAND2BXL g6670__6783(.AN (A_F[0]), .B (A_01[0]), .Y (n_175));
  NAND2BXL g6671__3680(.AN (A_F[2]), .B (A_01[2]), .Y (n_174));
  NOR2BX1 g6672__1617(.AN (A_01[1]), .B (A_F[1]), .Y (n_170));
  NAND2BXL g6673__2802(.AN (A_F[5]), .B (A_01[5]), .Y (n_173));
  NAND2BXL g6674__1705(.AN (A_F[4]), .B (A_01[4]), .Y (n_172));
  INVX1 g6676(.A (A_F[3]), .Y (n_168));
  DFFHQX1 \A_01_ff_reg[0] (.CK (osc_12), .D (n_142), .Q (A_01_ff[0]));
  DFFHQX1 \A_01_ff_reg[1] (.CK (osc_12), .D (n_165), .Q (A_01_ff[1]));
  DFFHQX1 \A_01_ff_reg[2] (.CK (osc_12), .D (n_164), .Q (A_01_ff[2]));
  DFFHQX1 \A_01_ff_reg[3] (.CK (osc_12), .D (n_162), .Q (A_01_ff[3]));
  DFFHQX1 \A_01_ff_reg[4] (.CK (osc_12), .D (n_161), .Q (A_01_ff[4]));
  DFFHQX1 \A_01_ff_reg[5] (.CK (osc_12), .D (n_152), .Q (A_01_ff[5]));
  DFFHQX1 \A_01_ff_reg[6] (.CK (osc_12), .D (n_154), .Q (A_01_ff[6]));
  DFFHQX1 \A_01_ff_reg[7] (.CK (osc_12), .D (n_160), .Q (A_01_ff[7]));
  DFFHQX1 \A_F_ff_reg[0] (.CK (osc_12), .D (n_140), .Q (A_F_ff[0]));
  DFFHQX1 \A_F_ff_reg[1] (.CK (osc_12), .D (n_159), .Q (A_F_ff[1]));
  DFFHQX1 \A_F_ff_reg[2] (.CK (osc_12), .D (n_156), .Q (A_F_ff[2]));
  DFFHQX1 \A_F_ff_reg[3] (.CK (osc_12), .D (n_158), .Q (A_F_ff[3]));
  DFFHQX1 \A_F_ff_reg[4] (.CK (osc_12), .D (n_157), .Q (A_F_ff[4]));
  DFFHQX1 \A_F_ff_reg[5] (.CK (osc_12), .D (n_151), .Q (A_F_ff[5]));
  DFFHQX1 \A_F_ff_reg[6] (.CK (osc_12), .D (n_153), .Q (A_F_ff[6]));
  DFFHQX1 \A_F_ff_reg[7] (.CK (osc_12), .D (n_155), .Q (A_F_ff[7]));
  SDFFRHQX1 \D_reg[0] (.RN (n_8), .CK (osc_12), .D (registerD_ff[0]),
       .SI (D[0]), .SE (dv_s), .Q (D[0]));
  SDFFRHQX1 \D_reg[1] (.RN (n_8), .CK (osc_12), .D (registerD_ff[1]),
       .SI (D[1]), .SE (dv_s), .Q (D[1]));
  SDFFRHQX1 \D_reg[2] (.RN (n_8), .CK (osc_12), .D (registerD_ff[2]),
       .SI (D[2]), .SE (dv_s), .Q (D[2]));
  SDFFRHQX1 \D_reg[3] (.RN (n_8), .CK (osc_12), .D (registerD_ff[3]),
       .SI (D[3]), .SE (dv_s), .Q (D[3]));
  DFFSHQX1 \counterD_ff_reg[0] (.SN (n_8), .CK (osc_12), .D (n_148), .Q
       (counterD_ff[0]));
  DFFSHQX1 \counterD_ff_reg[1] (.SN (n_8), .CK (osc_12), .D (n_149), .Q
       (counterD_ff[1]));
  DFFRHQX1 \current_state_reg[0] (.RN (n_8), .CK (osc_12), .D (n_163),
       .Q (current_state[0]));
  DFFHQX1 \inst_freq_div_counter_reg[0] (.CK (clk), .D (n_75), .Q
       (inst_freq_div_counter[0]));
  DFFHQX1 \inst_freq_div_counter_reg[1] (.CK (clk), .D (n_73), .Q
       (inst_freq_div_counter[1]));
  DFFHQX1 \inst_freq_div_counter_reg[2] (.CK (clk), .D (n_72), .Q
       (inst_freq_div_counter[2]));
  DFFHQX1 \inst_freq_div_counter_reg[3] (.CK (clk), .D (n_83), .Q
       (inst_freq_div_counter[3]));
  DFFHQX1 \inst_freq_div_counter_reg[4] (.CK (clk), .D (n_89), .Q
       (inst_freq_div_counter[4]));
  DFFHQX1 \inst_freq_div_counter_reg[5] (.CK (clk), .D (n_100), .Q
       (inst_freq_div_counter[5]));
  DFFHQX1 \inst_freq_div_counter_reg[6] (.CK (clk), .D (n_104), .Q
       (inst_freq_div_counter[6]));
  DFFHQX1 inst_freq_div_osc_12_reg(.CK (clk), .D (n_78), .Q (osc_12));
  DFFRHQX1 \regSignCount_ff_reg[0] (.RN (n_8), .CK (osc_12), .D (n_61),
       .Q (regSignCount_ff[0]));
  DFFRHQX1 \regSignCount_ff_reg[1] (.RN (n_8), .CK (osc_12), .D (n_79),
       .Q (regSignCount_ff[1]));
  DFFRHQX1 \regSignCount_ff_reg[2] (.RN (n_8), .CK (osc_12), .D (n_87),
       .Q (regSignCount_ff[2]));
  DFFRHQX1 \regSignCount_ff_reg[3] (.RN (n_8), .CK (osc_12), .D (n_98),
       .Q (regSignCount_ff[3]));
  DFFRHQX1 \regSignCount_ff_reg[4] (.RN (n_8), .CK (osc_12), .D
       (n_102), .Q (regSignCount_ff[4]));
  DFFRHQX1 \registerD_ff_reg[0] (.RN (n_8), .CK (osc_12), .D (n_126),
       .Q (registerD_ff[0]));
  DFFRHQX1 \registerD_ff_reg[1] (.RN (n_8), .CK (osc_12), .D (n_145),
       .Q (registerD_ff[1]));
  DFFRHQX1 \registerD_ff_reg[2] (.RN (n_8), .CK (osc_12), .D (n_146),
       .Q (registerD_ff[2]));
  DFFRHQX1 \registerD_ff_reg[3] (.RN (n_8), .CK (osc_12), .D (n_144),
       .Q (registerD_ff[3]));
  OAI221X1 g8236__5122(.A0 (n_4), .A1 (n_134), .B0 (counterSync_ff[0]),
       .B1 (n_121), .C0 (n_1), .Y (n_167));
  OAI21XL g8245__8246(.A0 (n_5), .A1 (n_134), .B0 (n_121), .Y (n_166));
  AO22X1 g8246__7098(.A0 (A_01_ff[1]), .A1 (n_138), .B0 (n_22), .B1
       (n_110), .Y (n_165));
  AO22X1 g8247__6131(.A0 (A_01_ff[2]), .A1 (n_137), .B0 (n_16), .B1
       (n_110), .Y (n_164));
  OAI2BB1X1 g8248__1881(.A0N (n_49), .A1N (n_112), .B0 (n_141), .Y
       (n_163));
  AO22X1 g8258__5115(.A0 (A_01_ff[3]), .A1 (n_136), .B0 (n_37), .B1
       (n_110), .Y (n_162));
  AO22X1 g8259__7482(.A0 (A_01_ff[4]), .A1 (n_135), .B0 (n_21), .B1
       (n_110), .Y (n_161));
  AO22X1 g8260__4733(.A0 (A_01_ff[7]), .A1 (n_132), .B0 (n_38), .B1
       (n_110), .Y (n_160));
  AO22X1 g8261__6161(.A0 (A_F_ff[1]), .A1 (n_138), .B0 (n_22), .B1
       (n_94), .Y (n_159));
  AO22X1 g8262__9315(.A0 (A_F_ff[3]), .A1 (n_136), .B0 (n_37), .B1
       (n_94), .Y (n_158));
  AO22X1 g8263__9945(.A0 (A_F_ff[4]), .A1 (n_135), .B0 (n_21), .B1
       (n_94), .Y (n_157));
  AO22X1 g8264__2883(.A0 (A_F_ff[2]), .A1 (n_137), .B0 (n_16), .B1
       (n_94), .Y (n_156));
  AO22X1 g8265__2346(.A0 (A_F_ff[7]), .A1 (n_132), .B0 (n_38), .B1
       (n_94), .Y (n_155));
  AO22X1 g8266__1666(.A0 (A_01_ff[6]), .A1 (n_131), .B0 (n_0), .B1
       (n_110), .Y (n_154));
  OAI22XL g8267__7410(.A0 (n_6), .A1 (n_130), .B0 (n_28), .B1 (n_93),
       .Y (n_153));
  OAI22XL g8268__6417(.A0 (n_15), .A1 (n_133), .B0 (n_29), .B1 (n_109),
       .Y (n_152));
  OAI22XL g8269__5477(.A0 (n_7), .A1 (n_133), .B0 (n_29), .B1 (n_93),
       .Y (n_151));
  OAI222XL g8270__2398(.A0 (n_3), .A1 (n_34), .B0 (n_45), .B1 (n_116),
       .C0 (counterA_ff[0]), .C1 (n_119), .Y (n_150));
  INVXL g8271(.A (n_147), .Y (n_149));
  OAI211X1 g8272__5107(.A0 (n_10), .A1 (n_35), .B0 (n_54), .C0 (n_122),
       .Y (n_148));
  AOI221X1 g8273__6260(.A0 (n_49), .A1 (n_114), .B0 (counterD_ff[1]),
       .B1 (n_36), .C0 (n_53), .Y (n_147));
  OAI2BB1X1 g8274__4319(.A0N (n_10), .A1N (n_113), .B0 (n_127), .Y
       (n_146));
  OAI31X1 g8275__8428(.A0 (n_10), .A1 (n_47), .A2 (n_108), .B0 (n_128),
       .Y (n_145));
  OAI2BB1X1 g8277__5526(.A0N (counterD_ff[0]), .A1N (n_113), .B0
       (n_129), .Y (n_144));
  OAI22XL g8278__6783(.A0 (n_25), .A1 (n_119), .B0 (n_11), .B1 (n_34),
       .Y (n_143));
  OAI2BB1X1 g8279__3680(.A0N (A_01_ff[0]), .A1N (n_125), .B0 (n_2), .Y
       (n_142));
  AOI22XL g8280__1617(.A0 (n_38), .A1 (n_120), .B0 (current_state[0]),
       .B1 (n_62), .Y (n_141));
  AO22X1 g8281__2802(.A0 (A_F_ff[0]), .A1 (n_125), .B0 (n_55), .B1
       (n_90), .Y (n_140));
  OAI22XL g8282__1705(.A0 (n_43), .A1 (n_119), .B0 (n_9), .B1 (n_34),
       .Y (n_139));
  NAND2XL g8283__5122(.A (n_22), .B (n_124), .Y (n_138));
  NAND2XL g8284__8246(.A (n_16), .B (n_124), .Y (n_137));
  NAND2XL g8285__7098(.A (n_37), .B (n_124), .Y (n_136));
  NAND2XL g8286__6131(.A (n_21), .B (n_124), .Y (n_135));
  AOI21XL g8287__1881(.A0 (n_48), .A1 (n_115), .B0 (n_207), .Y (n_134));
  NOR2XL g8288__5115(.A (n_29), .B (n_123), .Y (n_133));
  INVXL g8289(.A (n_130), .Y (n_131));
  OAI21XL g8290__7482(.A0 (n_44), .A1 (n_117), .B0 (registerD_ff[3]),
       .Y (n_129));
  OAI21XL g8291__4733(.A0 (n_47), .A1 (n_117), .B0 (registerD_ff[1]),
       .Y (n_128));
  OAI31X1 g8292__6161(.A0 (counterD_ff[0]), .A1 (n_44), .A2 (n_111),
       .B0 (registerD_ff[2]), .Y (n_127));
  OAI21XL g8293__9315(.A0 (n_54), .A1 (n_108), .B0 (n_118), .Y (n_126));
  NAND2XL g8294__9945(.A (n_38), .B (n_124), .Y (n_132));
  NOR2XL g8295__2883(.A (n_28), .B (n_123), .Y (n_130));
  INVXL g8296(.A (n_124), .Y (n_123));
  NAND2XL g8297__2346(.A (n_49), .B (n_117), .Y (n_122));
  NAND2BXL g8298__1666(.AN (n_116), .B (n_55), .Y (n_125));
  NOR2XL g8299__7410(.A (n_50), .B (n_116), .Y (n_124));
  INVXL g8300(.A (n_119), .Y (n_120));
  OAI21XL g8301__6417(.A0 (n_54), .A1 (n_111), .B0 (registerD_ff[0]),
       .Y (n_118));
  NAND2BXL g8302__5477(.AN (n_115), .B (n_48), .Y (n_121));
  NAND2BXL g8303__2398(.AN (n_116), .B (n_34), .Y (n_119));
  NAND2XL g8304__5107(.A (counterD_ff[0]), .B (n_112), .Y (n_117));
  NOR2XL g8305__6260(.A (n_90), .B (n_112), .Y (n_116));
  OAI2BB1X1 g8306__4319(.A0N (counterD_ff[1]), .A1N (counterD_ff[0]),
       .B0 (n_112), .Y (n_114));
  NAND3BXL g8307__8428(.AN (regSign[29]), .B (n_13), .C (n_107), .Y
       (n_115));
  NOR2XL g8309__5526(.A (n_44), .B (n_108), .Y (n_113));
  INVX1 g8310(.A (n_112), .Y (n_111));
  INVXL g8311(.A (n_110), .Y (n_109));
  OAI31X1 g8312__6783(.A0 (n_46), .A1 (n_76), .A2 (n_82), .B0 (n_108),
       .Y (n_112));
  NOR2XL g8313__3680(.A (n_50), .B (n_108), .Y (n_110));
  NAND4BXL g8315__1617(.AN (n_105), .B (regSign[20]), .C (regSign[21]),
       .D (regSign[22]), .Y (n_108));
  NOR4X1 g8316__2802(.A (regSign[30]), .B (regSign[28]), .C
       (regSign[19]), .D (n_103), .Y (n_107));
  OAI211X1 g8319__1705(.A0 (n_12), .A1 (n_63), .B0 (n_54), .C0 (n_1),
       .Y (n_106));
  NAND4XL g8321__5122(.A (regSign[23]), .B (regSign[24]), .C
       (regSign[25]), .D (n_97), .Y (n_105));
  NOR2XL g8322__8246(.A (n_67), .B (n_101), .Y (n_104));
  OR4X1 g8323__7098(.A (regSign[18]), .B (regSign[17]), .C
       (regSign[16]), .D (n_99), .Y (n_103));
  XNOR2X1 g8324__6131(.A (regSignCount_ff[4]), .B (n_95), .Y (n_102));
  XNOR2X1 g8327__1881(.A (inst_freq_div_counter[6]), .B (n_91), .Y
       (n_101));
  NOR2XL g8329__5115(.A (n_67), .B (n_92), .Y (n_100));
  NAND3BXL g8330__7482(.AN (regSign[31]), .B (n_68), .C (n_96), .Y
       (n_99));
  OA21X1 g8331__4733(.A0 (regSignCount_ff[3]), .A1 (n_86), .B0 (n_95),
       .Y (n_98));
  NOR4BBX1 g8332__6161(.AN (regSign[27]), .BN (regSign[26]), .C (n_70),
       .D (n_88), .Y (n_97));
  NOR4X1 g8334__9315(.A (regSign[14]), .B (regSign[15]), .C
       (regSign[13]), .D (n_85), .Y (n_96));
  INVXL g8337(.A (n_94), .Y (n_93));
  XNOR2X1 g8338__9945(.A (inst_freq_div_counter[5]), .B (n_81), .Y
       (n_92));
  NAND2XL g8339__2883(.A (regSignCount_ff[3]), .B (n_86), .Y (n_95));
  NOR2BX1 g8340__2346(.AN (n_90), .B (n_50), .Y (n_94));
  AND2X1 g8341__1666(.A (n_81), .B (inst_freq_div_counter[5]), .Y
       (n_91));
  NOR2XL g8342__7410(.A (n_84), .B (n_67), .Y (n_89));
  NOR2XL g8343__6417(.A (n_76), .B (n_88), .Y (n_90));
  NAND4BXL g8344__5477(.AN (n_80), .B (regSign[4]), .C (regSign[5]), .D
       (regSign[6]), .Y (n_88));
  AOI2BB1XL g8345__2398(.A0N (regSignCount_ff[2]), .A1N (n_77), .B0
       (n_86), .Y (n_87));
  OR2X1 g8348__5107(.A (regSign[12]), .B (n_82), .Y (n_85));
  XNOR2X1 g8349__6260(.A (inst_freq_div_counter[4]), .B (n_69), .Y
       (n_84));
  AND2X1 g8350__4319(.A (n_77), .B (regSignCount_ff[2]), .Y (n_86));
  NOR2XL g8351__8428(.A (n_74), .B (n_67), .Y (n_83));
  OR3X1 g8353__5526(.A (regSign[11]), .B (regSign[7]), .C (n_71), .Y
       (n_82));
  AND2X1 g8354__6783(.A (n_69), .B (inst_freq_div_counter[4]), .Y
       (n_81));
  NAND4BXL g8358__3680(.AN (n_64), .B (regSign[7]), .C (regSign[8]), .D
       (regSign[9]), .Y (n_80));
  AOI2BB1XL g8359__1617(.A0N (regSignCount_ff[1]), .A1N (n_60), .B0
       (n_77), .Y (n_79));
  OAI211X1 g8360__2802(.A0 (osc_12), .A1 (n_65), .B0 (n_8), .C0 (n_66),
       .Y (n_78));
  NOR2XL g8361__1705(.A (inst_freq_div_counter[0]), .B (n_67), .Y
       (n_75));
  AND2X1 g8362__5122(.A (n_60), .B (regSignCount_ff[1]), .Y (n_77));
  NAND2BXL g8364__8246(.AN (n_70), .B (n_68), .Y (n_76));
  XNOR2X1 g8365__7098(.A (inst_freq_div_counter[3]), .B (n_56), .Y
       (n_74));
  NOR2XL g8366__6131(.A (n_27), .B (n_67), .Y (n_73));
  NOR2XL g8367__1881(.A (n_57), .B (n_67), .Y (n_72));
  OR4X1 g8368__5115(.A (regSign[10]), .B (regSign[8]), .C (regSign[9]),
       .D (n_59), .Y (n_71));
  NAND3BXL g8369__7482(.AN (regSign[16]), .B (regSign[31]), .C (n_58),
       .Y (n_70));
  AND2X1 g8370__4733(.A (n_56), .B (inst_freq_div_counter[3]), .Y
       (n_69));
  NAND2XL g8371__6161(.A (osc_12), .B (n_65), .Y (n_66));
  NOR4X1 g8372__9315(.A (regSign[26]), .B (regSign[27]), .C
       (regSign[25]), .D (n_52), .Y (n_68));
  NAND2XL g8373__9945(.A (n_8), .B (n_65), .Y (n_67));
  NAND4BXL g8374__2883(.AN (n_46), .B (regSign[10]), .C (regSign[11]),
       .D (n_31), .Y (n_64));
  NAND4BXL g8375__2346(.AN (n_42), .B (inst_freq_div_counter[5]), .C
       (inst_freq_div_counter[4]), .D (n_14), .Y (n_65));
  INVXL g8376(.A (n_62), .Y (n_63));
  AOI2BB1XL g8377__1666(.A0N (regSignCount_ff[0]), .A1N (n_51), .B0
       (n_60), .Y (n_61));
  NAND3BXL g8378__7410(.AN (n_48), .B (n_33), .C (n_13), .Y (n_62));
  OR4X1 g8379__6417(.A (regSign[6]), .B (regSign[5]), .C (regSign[4]),
       .D (n_32), .Y (n_59));
  AND2X1 g8380__5477(.A (n_51), .B (regSignCount_ff[0]), .Y (n_60));
  NOR4X1 g8381__2398(.A (regSign[17]), .B (regSign[18]), .C
       (regSign[19]), .D (n_26), .Y (n_58));
  XNOR2X1 g8382__5107(.A (inst_freq_div_counter[2]), .B (n_17), .Y
       (n_57));
  INVX1 g8383(.A (n_53), .Y (n_54));
  NAND2BXL g8384__6260(.AN (regSign[24]), .B (n_41), .Y (n_52));
  AND2X1 g8385__4319(.A (n_17), .B (inst_freq_div_counter[2]), .Y
       (n_56));
  NOR2XL g8386__8428(.A (reset), .B (n_45), .Y (n_55));
  NOR2XL g8387__5526(.A (counterD_ff[0]), .B (n_47), .Y (n_53));
  OAI211X1 g8388__6783(.A0 (current_state[1]), .A1 (n_39), .B0 (n_207),
       .C0 (n_23), .Y (n_51));
  NAND3BXL g8389__3680(.AN (reset), .B (n_40), .C (n_34), .Y (n_50));
  OAI21XL g8390__1617(.A0 (n_10), .A1 (n_36), .B0 (n_44), .Y (n_49));
  NOR3BXL g8391__2802(.AN (n_206), .B (n_207), .C (n_30), .Y (n_48));
  OR2X1 g8396__1705(.A (counterD_ff[1]), .B (n_36), .Y (n_47));
  AOI21XL g8397__5122(.A0 (counterA_ff[2]), .A1 (n_18), .B0 (n_37), .Y
       (n_43));
  NAND4BXL g8398__8246(.AN (inst_freq_div_counter[1]), .B
       (inst_freq_div_counter[3]), .C (inst_freq_div_counter[2]), .D
       (inst_freq_div_counter[6]), .Y (n_42));
  NOR4X1 g8399__7098(.A (regSign[23]), .B (regSign[20]), .C
       (regSign[22]), .D (regSign[21]), .Y (n_41));
  NAND4XL g8400__6131(.A (regSign[14]), .B (regSign[15]), .C
       (regSign[13]), .D (regSign[12]), .Y (n_46));
  NAND2XL g8401__1881(.A (n_24), .B (n_39), .Y (n_45));
  NAND2XL g8402__5115(.A (counterD_ff[1]), .B (n_35), .Y (n_44));
  INVXL g8403(.A (n_39), .Y (n_40));
  INVX1 g8404(.A (n_35), .Y (n_36));
  NAND2XL g8405__7482(.A (n_207), .B (n_23), .Y (n_33));
  AND2X1 g8406__4733(.A (n_21), .B (n_9), .Y (n_39));
  NOR2XL g8407__6161(.A (n_9), .B (n_18), .Y (n_38));
  NOR2XL g8408__9315(.A (counterA_ff[2]), .B (n_18), .Y (n_37));
  NOR2XL g8409__9945(.A (n_23), .B (n_208), .Y (n_35));
  AND2X1 g8410__2883(.A (n_13), .B (n_24), .Y (n_34));
  INVXL g8411(.A (n_31), .Y (n_32));
  INVXL g8413(.A (n_0), .Y (n_28));
  XNOR2X1 g8414__2346(.A (inst_freq_div_counter[0]), .B
       (inst_freq_div_counter[1]), .Y (n_27));
  NAND3XL g8415__1666(.A (regSign[28]), .B (regSign[30]), .C
       (regSign[29]), .Y (n_26));
  NOR2XL g8416__7410(.A (n_20), .B (n_19), .Y (n_25));
  NOR4X1 g8417__6417(.A (regSign[3]), .B (regSign[1]), .C (regSign[2]),
       .D (regSign[0]), .Y (n_31));
  NOR3XL g8418__5477(.A (counterSync_ff[1]), .B (counterSync_ff[0]), .C
       (n_208), .Y (n_30));
  NAND2XL g8419__2398(.A (counterA_ff[2]), .B (n_19), .Y (n_29));
  NOR2XL g8421__5107(.A (current_state[0]), .B (current_state[1]), .Y
       (n_24));
  NAND2XL g8422__6260(.A (current_state[0]), .B (n_12), .Y (n_23));
  NOR2XL g8423__4319(.A (counterA_ff[1]), .B (counterA_ff[2]), .Y
       (n_22));
  NOR2XL g8424__8428(.A (counterA_ff[1]), .B (counterA_ff[0]), .Y
       (n_21));
  NOR2XL g8426__5526(.A (counterA_ff[0]), .B (n_11), .Y (n_20));
  NOR2XL g8427__6783(.A (counterA_ff[1]), .B (n_3), .Y (n_19));
  NAND2XL g8428__3680(.A (counterA_ff[1]), .B (counterA_ff[0]), .Y
       (n_18));
  AND2X1 g8429__1617(.A (inst_freq_div_counter[0]), .B
       (inst_freq_div_counter[1]), .Y (n_17));
  NOR2XL g8430__2802(.A (counterA_ff[0]), .B (counterA_ff[2]), .Y
       (n_16));
  INVXL g8431(.A (A_01_ff[5]), .Y (n_15));
  INVXL g8432(.A (inst_freq_div_counter[0]), .Y (n_14));
  INVX1 g8433(.A (n_208), .Y (n_13));
  INVX1 g8436(.A (counterD_ff[0]), .Y (n_10));
  INVX1 g8438(.A (reset), .Y (n_8));
  INVXL g8439(.A (A_F_ff[5]), .Y (n_7));
  INVXL g8440(.A (A_F_ff[6]), .Y (n_6));
  NAND2BX1 g2__1705(.AN (n_108), .B (n_55), .Y (n_2));
  NAND4BBXL g8444__5122(.AN (n_76), .BN (n_207), .C (n_30), .D (n_96),
       .Y (n_1));
  NOR2BX1 g8445__8246(.AN (n_20), .B (n_9), .Y (n_0));
  DFFRX1 \current_state_reg[1] (.RN (n_8), .CK (osc_12), .D (n_106), .Q
       (current_state[1]), .QN (n_12));
  DFFRX1 \counterA_ff_reg[1] (.RN (n_8), .CK (osc_12), .D (n_143), .Q
       (counterA_ff[1]), .QN (n_11));
  DFFRX1 \counterA_ff_reg[2] (.RN (n_8), .CK (osc_12), .D (n_139), .Q
       (counterA_ff[2]), .QN (n_9));
  DFFRX1 \counterSync_ff_reg[1] (.RN (n_8), .CK (osc_12), .D (n_166),
       .Q (counterSync_ff[1]), .QN (n_5));
  DFFRX1 \counterSync_ff_reg[0] (.RN (n_8), .CK (osc_12), .D (n_167),
       .Q (counterSync_ff[0]), .QN (n_4));
  DFFRX1 \counterA_ff_reg[0] (.RN (n_8), .CK (osc_12), .D (n_150), .Q
       (counterA_ff[0]), .QN (n_3));
endmodule

